---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-autoscaler
  namespace: exoscale
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-autoscaler-secret-sync
rules:
- apiGroups: [""]
  resources:
  - secrets
  verbs:
  - 'delete'
  - 'create'
  - 'patch'
  - 'get'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-autoscaler-secret-sync
subjects:
- kind: ServiceAccount
  name: cluster-autoscaler
  namespace: exoscale
roleRef:
  kind: ClusterRole
  name: cluster-autoscaler-secret-sync
  apiGroup: ""
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cluster-autoscaler-secret-sync
  namespace: exoscale
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/role: "cluster-autoscaler"

        vault.hashicorp.com/agent-inject-secret-exoscale: "iam/exoscale/apikey/cluster-autoscaler"
        vault.hashicorp.com/agent-inject-template-exoscale: |
          {{- with secret "iam/exoscale/apikey/cluster-autoscaler" -}}
          export EXOSCALE_API_KEY={{ .Data.api_key }}
          export EXOSCALE_API_SECRET={{ .Data.api_secret }}
          {{- end }}

        vault.hashicorp.com/agent-revoke-on-shutdown: "true"
        vault.hashicorp.com/agent-limits-cpu: "50m"
        vault.hashicorp.com/agent-requests-cpu: "50m"
        vault.hashicorp.com/tls-secret: "vault-sidecar-tls"
        vault.hashicorp.com/ca-cert: "/vault/tls/ca.pem"
        vault.hashicorp.com/log-level: "debug"
    spec:
      serviceAccountName: cluster-autoscaler
      containers:
      - command:
        - /bin/sh
        - -c
        - |-
          . /vault/secrets/exoscale

          cat <<EOF | kubectl apply -f -
          apiVersion: v1
          kind: Secret
          metadata:
            name: exoscale-api-credentials
            namespace: kube-system
          type: Opaque
          stringData:
            api-key: $EXOSCALE_API_KEY
            api-secret: $EXOSCALE_API_SECRET
          EOF
        image: bitnami/kubectl:latest
        imagePullPolicy: Always
        name: cluster-autoscaler-secret-sync
        securityContext:
          procMount: Default
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: true
        resources:
          requests:
            cpu: 0.1
            memory: 100Mi
          limits:
            memory: 100Mi
      restartPolicy: Never
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cluster-autoscaler-secret-sync
  namespace: exoscale
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  schedule: 0 */1 * * *
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            vault.hashicorp.com/agent-inject: "true"
            vault.hashicorp.com/agent-pre-populate-only: "true"
            vault.hashicorp.com/role: "cluster-autoscaler"

            vault.hashicorp.com/agent-inject-secret-exoscale: "iam/exoscale/apikey/cluster-autoscaler"
            vault.hashicorp.com/agent-inject-template-exoscale: |
              {{- with secret "iam/exoscale/apikey/cluster-autoscaler" -}}
              export EXOSCALE_API_KEY={{ .Data.api_key }}
              export EXOSCALE_API_SECRET={{ .Data.api_secret }}
              {{- end }}

            vault.hashicorp.com/agent-revoke-on-shutdown: "true"
            vault.hashicorp.com/agent-limits-cpu: "50m"
            vault.hashicorp.com/agent-requests-cpu: "50m"
            vault.hashicorp.com/tls-secret: "vault-sidecar-tls"
            vault.hashicorp.com/ca-cert: "/vault/tls/ca.pem"
            vault.hashicorp.com/log-level: "debug"
        spec:
          serviceAccountName: cluster-autoscaler
          containers:
          - command:
            - /bin/sh
            - -c
            - |-
              . /vault/secrets/exoscale

              cat <<EOF | kubectl apply -f -
              apiVersion: v1
              kind: Secret
              metadata:
                name: exoscale-api-credentials
                namespace: kube-system
              type: Opaque
              stringData:
                api-key: $EXOSCALE_API_KEY
                api-secret: $EXOSCALE_API_SECRET
              EOF
            image: bitnami/kubectl:latest
            imagePullPolicy: Always
            name: cluster-autoscaler-secret-sync
            securityContext:
              procMount: Default
              runAsNonRoot: true
              runAsUser: 1000
              readOnlyRootFilesystem: true
            resources:
              requests:
                cpu: 0.1
                memory: 100Mi
              limits:
                memory: 100Mi
          restartPolicy: Never
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-sidecar-tls
  namespace: exoscale
type: Opaque
data:
  ca.pem: $vault:cluster_ca_cert$
