---

- name: Add etcd group
  become: true
  group:
    name: "{{ etcd_group }}"
    state: present

- name: Add etcd user
  become: true
  user:
    name: "{{ etcd_user }}"
    comment: "etcd user"
    group: "{{ etcd_group }}"
    groups: "{{ etcd_groups }}"
    shell: /bin/bash
    system: true

# Binary installation

- name: Check etcd installation
  shell: command -v etcd
  environment:
    PATH: "{{ etcd_bin_path }}:{{ ansible_env.PATH }}"
  register: etcd_installation
  changed_when: false
  ignore_errors: true
  check_mode: false
  tags:
    - skip_ansible_lint  # command is a shell builtin

- name: Install OS packages and Etcd
  include_tasks: _install.yml

- name: systemd unit
  tags:
    - etcd
  become: true
  template:
    src: "etcd.service.j2"
    dest: "/etc/systemd/system/etcd.service"
    force: true
    owner: root
    group: root
    mode: "0644"
  notify: reload systemd

- name: Insert etcdctl source in dotfile
  tags:
    - etcd
  become: true
  lineinfile:
    path: "{{ etcd_home }}/{{ etcd_dotfile }}"
    line: ". /etc/default/etcdctl"
    owner: "{{ etcd_user }}"
    group: "{{ etcd_group }}"
    create: true
    mode: 0600
  when:
    - not etcd_dotfile_disable

- name: Install additional templated files
  tags:
    - etcd
  become: true
  template:
    src: "{{ item.name }}.j2"
    dest: "{{ item.dest }}/{{ item.name }}"
    force: true
    owner: "{{ etcd_user }}"
    group: "{{ etcd_group }}"
    mode: "{{ item.mode }}"
  loop:
    - {name: 'etcdctl', dest: "/etc/default", mode: "0600"}
    - {name: 'base-environment', dest: "{{ etcd_config_path }}", mode: "0600"}

- name: Install healthcheck script
  tags:
    - etcd
  become: true
  copy:
    src: "etcd-healthcheck"
    dest: "{{ etcd_bin_path }}/etcd-healthcheck"
    force: true
    owner: root
    group: root
    mode: "0777"
