patches:
  - target:
      kind: Deployment
      name: coredns-coredns
    patch: |-
      - op: replace
        path: /spec/strategy/rollingUpdate
        value:
          maxUnavailable: 1
  - target:
      kind: ClusterRole
      name: coredns-coredns
    patch: |-
      - op: replace
        path: /metadata/name
        value: coredns
  - target:
      kind: ClusterRoleBinding
      name: coredns-coredns
    patch: |-
      - op: replace
        path: /metadata/name
        value: coredns
  - target:
      kind: ConfigMap
      name: coredns-coredns
    patch: |-
      - op: replace
        path: /metadata/name
        value: coredns
  - target:
      kind: Service
      name: coredns-coredns
    patch: |-
      - op: replace
        path: /metadata/name
        value: coredns
  - target:
      kind: Deployment
      name: coredns-coredns
    patch: |-
      - op: replace
        path: /metadata/name
        value: coredns
  - target:
      kind: Service
      name: coredns-coredns
    patch: |-
      - op: replace
        path: /spec/clusterIP
        value: $kubernetes:dns_service_ipv4$

helmGlobals:
  chartHome: .helm
  configHome: .helm

helmCharts:
- name: coredns
  repo: https://coredns.github.io/helm
  releaseName: coredns
  namespace: kube-system
  version: 1.19.4
  valuesInline:
    servers:
    - zones:
      - zone: .
      port: 53
      # If serviceType is nodePort you can specify nodePort here
      # nodePort: 30053
      plugins:
      - name: errors
      # Serves a /health endpoint on :8080, required for livenessProbe
      - name: health
        configBlock: |-
          lameduck 5s
      # Serves a /ready endpoint on :8181, required for readinessProbe
      - name: ready
      # Required to query kubernetes API for data
      - name: kubernetes
        parameters: $kubernetes:cluster_domain$ in-addr.arpa ip6.arpa
        configBlock: |-
          pods verified
          fallthrough in-addr.arpa ip6.arpa
          ttl 30
      # Serves a /metrics endpoint on :9153, required for serviceMonitor
      - name: prometheus
        parameters: 0.0.0.0:9153
      - name: forward
        parameters: . /etc/resolv.conf
      - name: cache
        parameters: 30
      - name: loop
      - name: reload
      - name: loadbalance
    replicaCount: 2
    priorityClassName: system-cluster-critical
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: kubernetes.io/hostname
          labelSelector:
            matchLabels:
              k8s-app: kube-dns