---

- name: Check exo-cli package checksum file
  tags:
    - exo-cli
  stat:
    path: "/tmp/{{ exoscale_cli_shasums }}"
  become: false
  register: exoscale_cli_checksum

- name: Get exo-cli package checksum file
  tags:
    - exo-cli
  get_url:
    url: "{{ exoscale_cli_checksum_file_url }}"
    dest: "/tmp/{{ exoscale_cli_shasums }}"
  when: not exoscale_cli_checksum.stat.exists | bool

- name: Get exo-cli package checksum
  tags:
    - exo-cli
    - skip_ansible_lint
  shell: |
    set -o pipefail
    grep "{{ exoscale_cli_pkg }}" "/tmp/{{ exoscale_cli_shasums }}" | awk '{print $1}'
  args:
    executable: /bin/bash
  changed_when: false
  become: false
  register: exoscale_cli_sha256

- name: Check exo-cli package file
  tags:
    - exo-cli
  stat:
    path: "/tmp/{{ exoscale_cli_pkg }}"
  become: false
  register: exoscale_cli_package

- name: "Download exo-cli → {{ exoscale_cli_tgz_url }}"
  tags:
    - exo-cli
  get_url:
    url: "{{ exoscale_cli_tgz_url }}"
    dest: "/tmp/{{ exoscale_cli_pkg }}"
    checksum: "sha256:{{ exoscale_cli_sha256.stdout }}"
    timeout: "42"
  when: not exoscale_cli_package.stat.exists | bool

- name: Unarchive exo
  tags:
    - exo-cli
  unarchive:
    remote_src: true
    src: "/tmp/{{ exoscale_cli_pkg }}"
    dest: "/tmp"
    creates: "/tmp/exo"

- name: Install exo
  tags:
    - exo-cli
  become: true
  copy:
    remote_src: true
    src: "/tmp/exo"
    dest: "{{ exoscale_cli_bin_path }}"
    owner: "root"
    group: "root"
    mode: "0755"
