---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: konnectivity-agent
spec:
  destination:
    name: ''
    namespace: kube-system
    server: 'https://kubernetes.default.svc'
  source:
    path: "{{ .Values.deployment.konnectivityAgent.path }}"
    repoURL: "{{ .Values.deployment.konnectivityAgent.repoURL }}"
    targetRevision: "{{ .Values.deployment.konnectivityAgent.targetRevision }}"
    helm:
      values: |-
        platform:
          domain: "{{ .Values.platform.domain }}"
          kubernetes:
            cluster:
              domain: "{{ .Values.platform.kubernetes.cluster.domain }}"
            proxyserver:
              address0: "{{ .Values.platform.kubernetes.proxyserver.address0 }}"
              address1: "{{ .Values.platform.kubernetes.proxyserver.address1 }}"
  project: "{{ .Values.core.projectName }}"
  syncPolicy:
    automated:
      prune: false
      selfHeal: {{ .Values.deployment.konnectivityAgent.selfHeal }}
