---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
spec:
  destination:
    name: ''
    namespace: kube-system
    server: 'https://kubernetes.default.svc'
  source:
    path: "{{ .Values.deployment.metricsServer.path }}"
    repoURL: "{{ .Values.deployment.metricsServer.repoURL }}"
    targetRevision: "{{ .Values.deployment.metricsServer.targetRevision }}"
    helm:
      values: |-
        platform:
          domain: "{{ .Values.platform.domain }}"
          vault:
            aggregationLayerPKIPath: "{{ .Values.platform.vault.aggregationLayerPKIPath }}"
            baseUrl: "{{ .Values.platform.vault.baseUrl }}"
            caCert: |
              {{- .Values.platform.vault.caCert | nindent 14 }}
          kubernetes:
            kubelet:
              caCert: |
                {{- .Values.platform.kubernetes.kubelet.caCert | nindent 16 }}
            aggregationLayer:
              caCert: |
                {{- .Values.platform.kubernetes.aggregationLayer.caCert | nindent 16 }}

  project: "{{ .Values.core.projectName }}"
  syncPolicy:
    automated:
      prune: false
      selfHeal: {{ .Values.deployment.metricsServer.selfHeal }}
