---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dex
spec:
  destination:
    name: ''
    namespace: dex
    server: 'https://kubernetes.default.svc'
  source:
    path: "{{ .Values.deployment.dex.path }}"
    repoURL: "{{ .Values.deployment.dex.repoURL }}"
    targetRevision: "{{ .Values.deployment.dex.targetRevision }}"
    helm:
      values: |-
        platform:
          domain: "{{ .Values.platform.domain }}"
          argocd:
            hostname: "{{ .Values.platform.argocd.hostname }}"
            oidc:
              clientSecret: "{{ .Values.platform.argocd.oidc.clientSecret }}"
          vault:
            caCert: |
              {{- .Values.platform.vault.caCert | nindent 14 }}
          dex:
            hostname: "{{ .Values.platform.dex.hostname }}"
            ingressClassName: "{{ .Values.platform.dex.ingressClassName }}"
            oidc:
              issuer: "{{ .Values.platform.dex.oidc.issuer }}"
              clientID: "{{ .Values.platform.dex.oidc.clientID }}"
              clientSecret: "{{ .Values.platform.dex.oidc.clientSecret }}"
            caCert: |
              {{- .Values.platform.dex.caCert | nindent 14 }}

  project: "{{ .Values.core.projectName }}"
  syncPolicy:
    automated:
      prune: false
      selfHeal: {{ .Values.deployment.dex.selfHeal }}
