---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: network-policies
  annotations:
    argocd.argoproj.io/sync-wave: "6" # TODO: set to 3 once fully functionnal
spec:
  destination:
    name: ''
    namespace: kube-system
    server: 'https://kubernetes.default.svc'
  source:
    path: "{{ .Values.deployment.networkPolicies.path }}"
    repoURL: "{{ .Values.deployment.networkPolicies.repoURL }}"
    targetRevision: "{{ .Values.deployment.networkPolicies.targetRevision }}"
    helm:
      values: |-
        platform:
          domain: "{{ .Values.platform.domain }}"
          dex:
            publicIP: "{{ .Values.platform.dex.publicIP }}"
          vault:
            publicIP: "{{ .Values.platform.vault.publicIP }}"

  project: "{{ .Values.core.projectName }}"
  syncPolicy:
    automated:
      prune: false
      selfHeal: {{ .Values.deployment.networkPolicies.selfHeal }}