---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    name: ''
    # namespace: namespaces
    server: 'https://kubernetes.default.svc'
  source:
    path: "{{ .Values.deployment.namespaces.path }}"
    repoURL: "{{ .Values.deployment.namespaces.repoURL }}"
    targetRevision: "{{ .Values.deployment.namespaces.targetRevision }}"
    helm:
      values: |-
        platform:
          domain: "{{ .Values.platform.domain }}"
        ingresses:
{{- range .Values.ingresses }}
          - {{ . }}
{{- end }}
        app:
          namespaces:
{{- range .Values.namespaces }}
            - name: {{ .name }}
              quota:
                requests:
                  cpu: {{ .quota_cpu_request }}
                  memory: {{ .quota_memory_request }}
                limits:
                  memory: {{ .quota_memory_limit }}
                pods: {{ .quota_pods }}
              defaults:
                requests:
                  cpu: {{ .default_cpu_request }}
                  memory: {{ .default_memory_request }}
                limits:
                  memory: {{ .default_memory_limit }}
              users:
{{- range .users }}
                - {{ . }}
{{- end }}
{{- end }}
  project: "{{ .Values.core.projectName }}"
  syncPolicy:
    automated:
     prune: false
     selfHeal: {{ .Values.deployment.namespaces.selfHeal }}
