---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    name: ''
    namespace: kyverno
    server: 'https://kubernetes.default.svc'
  source:
    path: "{{ .Values.deployment.kyverno.path }}"
    repoURL: "{{ .Values.deployment.kyverno.repoURL }}"
    targetRevision: "{{ .Values.deployment.kyverno.targetRevision }}"
    helm:
      values: |-
        platform:
          domain: "{{ .Values.platform.domain }}"
  project: "{{ .Values.core.projectName }}"
  syncPolicy:
    automated:
      prune: false
      selfHeal: {{ .Values.deployment.kyverno.selfHeal }}
    syncOptions:
      - Replace=true
