---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coredns
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  destination:
    name: ''
    namespace: kube-system
    server: 'https://kubernetes.default.svc'
  source:
    path: "{{ .Values.deployment.coredns.path }}"
    repoURL: "{{ .Values.deployment.coredns.repoURL }}"
    targetRevision: "{{ .Values.deployment.coredns.targetRevision }}"
    helm:
      values: |-
        platform:
          domain: "{{ .Values.platform.domain }}"
          kubernetes:
            cluster:
              domain: "{{ .Values.platform.kubernetes.cluster.domain }}"
              dnsServiceIPv4: "{{ .Values.platform.kubernetes.cluster.dnsServiceIPv4 }}"
              dnsServiceIPv6: "{{ .Values.platform.kubernetes.cluster.dnsServiceIPv6 }}"
  project: "{{ .Values.core.projectName }}"
  syncPolicy:
    automated:
      prune: false
      selfHeal: {{ .Values.deployment.coredns.selfHeal }}
