---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: "{{ .Values.deployment.argocd.path }}"
    repoURL: "{{ .Values.deployment.argocd.repoURL }}"
    targetRevision: "{{ .Values.deployment.argocd.targetRevision }}"
    helm:
      values: |-
        platform:
          domain: "{{ .Values.platform.domain }}"
          argocd:
            hostname: "{{ .Values.platform.argocd.hostname }}"
            ingressClassName: "{{ .Values.platform.argocd.ingressClassName }}"
            oidc:
              clientSecret: "{{ .Values.platform.argocd.oidc.clientSecret }}"
            policy: |
              {{- .Values.platform.argocd.policy | nindent 14 }}
          dex:
            hostname: "{{ .Values.platform.dex.hostname }}"
            caCert: |
              {{- .Values.platform.dex.caCert | nindent 14 }}

  project: "{{ .Values.core.projectName }}"
  syncPolicy:
    automated:
      prune: false
      selfHeal: {{ .Values.deployment.argocd.selfHeal }}
