core:
  projectName:

deployment:
  certManagerDns01Cloudflare:
    path:
    repoURL:
    targetRevision:
    selfHeal:
  externalDnsCloudflare:
    path:
    repoURL:
    targetRevision:
    selfHeal:
  certMmanagerHttp01:
    path:
    repoURL:
    targetRevision:
    selfHeal:
  certManagerSelfsigned:
    path:
    repoURL:
    targetRevision:
    selfHeal:
  nginxIngressController:
    path:
    repoURL:
    targetRevision:
    selfHeal:

platform:
  domain:
  ingress:
    name:
    domain:
    cloudflare:
      apiToken:
    loadbalancerIP:
    label:
      name:
      value:
    taint:
      name:
      value:
