helmGlobals:
  chartHome: .helm
  configHome: .helm

helmCharts:
- name: cilium
  repo: https://helm.cilium.io/
  releaseName: cilium
  namespace: kube-system
  version: 1.13.2
  valuesInline:
    image:
      pullPolicy: Always

    resources:
      limits:
        memory: 512Mi
      requests:
        cpu: 50m
        memory: 192Mi

    cni:
      chainingMode: portmap

    containerRuntime:
      integration: containerd

    hostServices:
      enabled: true

    nodePort:
      enabled: true

    externalIPs:
      enabled: true

    hostPort:
      enabled: true

    k8sServiceHost: "${ kubernetes_api_address }"
    k8sServicePort: "6443"
    kubeProxyReplacement: strict

    hubble:
      enabled: false

    ipam:
      operator:
        clusterPoolIPv4PodCIDR: "${ kubernetes_pod_network_inet4_cidr }"
        # clusterPoolIPv6PodCIDR: "${ kubernetes_pod_network_inet6_cidr }"

    ipv4:
      enabled: true

    ipv6:
      enabled: false # TODO: fix ipv6 support

    policyEnforcementMode: "always"
    policyAuditMode: true

    operator:
      image:
        pullPolicy: Always
      podDisruptionBudget:
        enabled: true
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: io.cilium/app
                operator: In
                values:
                - operator
            topologyKey: kubernetes.io/hostname
      resources:
        limits:
          cpu: 50m
          memory: 50Mi
        requests:
          cpu: 50m
          memory: 50Mi

    cgroup:
      hostRoot: /sys/fs/cgroup
      autoMount:
        enabled: false
