---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "{{ .Values.platform.ingress.name }}-wildcard"
spec:
  secretName: "{{ .Values.platform.ingress.name }}-wildcard"
  duration: "2160h0m0s"
  renewBefore: "1440h0m0s"
  issuerRef:
    name: "dns01-{{ .Values.platform.ingress.name }}"
    kind: ClusterIssuer
  commonName: "*.{{ .Values.platform.ingress.domain }}"
  dnsNames:
    - "*.{{ .Values.platform.ingress.domain }}"
