---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: "dns01-{{ .Values.platform.ingress.name }}"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: "{{ .Values.platform.ingress.name }}-dns01-issuer-private-key"
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: "{{ .Values.platform.ingress.name }}-cloudflare-api-token"
            key: api-token