---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.platform.ingress.name }}-cloudflare-api-token"
  namespace: cert-manager
data:
  api-token: "{{ .Values.platform.ingress.cloudflare.apiToken |b64enc }}"