---

- name: Install Kubernetes Controller Manager and Vault agent
  hosts: default
  become: true
  vars:
    # vault agent
    vault_config_path: /etc/vault
    vault_tls_config_path: /var/vault/tls
    vault_service_name: vault-agent
    vault_mode: agent
    vault_user: kubernetes
    vault_group: kubernetes
    # kubernetes apiserver healthcheck reverse-proxy for the Network Load Balancer
    healthcheck_port: 6444
    healthcheck_user: "{{ kube_apiserver_user }}"
    healthcheck_group: "{{ kube_apiserver_group }}"
    healthcheck_script_path: "{{ kube_apiserver_bin_path }}/kube-healthcheck"
    # etcd endpoints probe
    etcd_server: false # needs client only
    etcd_user: "{{ kube_apiserver_user }}"
    etcd_group: "{{ kube_apiserver_group }}"
    etcd_groups: null
    etcd_dotfile_disable: true
    # kubernetes control plane components integration with vault agent
    vault_agent_kube_control_plane_auth_path: auth/exoscale
    vault_agent_config_template: "{{ playbook_dir }}/defaults/templates/vault-agent-exoscale-kube-control-plane.hcl.j2"
    vault_agent_approle_path: /var/vault
    vault_agent_secrets:
      kv_exoscale_cloud_controller_manager_exoscale_api: 'kv/platform/exoscale/cloud-controller-manager'
      kv_cluster_autoscaler_exoscale_api: 'kv/platform/exoscale/cluster-autoscaler'
      kv_kubelet_pki: 'kv/platform/kubernetes/kubelet-pki'
      kv_secrets_encryption: 'kv/platform/kubernetes/secret-encryption'
      kv_serviceaccount: 'kv/platform/kubernetes/service-account'
      pki_aggregationlayer_ca_chain: 'pki/platform/kubernetes/aggregation-layer/cert/ca_chain'
      pki_aggregationlayer_cert_apiserver: 'pki/platform/kubernetes/aggregation-layer/issue/apiserver'
      pki_client_ca_chain: 'pki/platform/kubernetes/client/cert/ca_chain'
      pki_client_cert_admin: 'pki/platform/kubernetes/client/issue/operator-admin'
      pki_controlplane_ca_chain: 'pki/platform/kubernetes/control-plane/cert/ca_chain'
      pki_controlplane_cert_apiserver: 'pki/platform/kubernetes/control-plane/issue/apiserver'
      pki_controlplane_cert_cloud_controller_manager: 'pki/platform/kubernetes/control-plane/issue/cloud-controller-manager'
      pki_controlplane_cert_cluster_autoscaler: 'pki/platform/kubernetes/control-plane/issue/cluster-autoscaler'
      pki_controlplane_cert_controller_manager: 'pki/platform/kubernetes/control-plane/issue/controller-manager'
      pki_controlplane_cert_konnectivity: 'pki/platform/kubernetes/control-plane/issue/konnectivity'
      pki_controlplane_cert_scheduler: 'pki/platform/kubernetes/control-plane/issue/scheduler'
      pki_etcd_cert_apiserver: 'pki/platform/kubernetes/etcd/issue/apiserver'
      pki_konnectivity_cert_cluster: 'pki/platform/kubernetes/control-plane/issue/konnectivity-server-cluster'
      pki_kubelet_ca_chain: 'pki/platform/kubernetes/kubelet/cert/ca_chain'
      pki_kubelet_cert_apiserver: 'pki/platform/kubernetes/kubelet/issue/apiserver'
      pki_oidc_ca_chain: 'pki/platform/deployment/core/cert/ca_chain'
    # monitoring
    ssl_exporter_kubeconfigs:
      cloud-controller-manager-kubeconfig: "{{ exoscale_cloud_controller_manager_config_path }}/cloud-controller-manager.kubeconfig"
      cluster-autoscaler-kubeconfig: "{{ cluster_autoscaler_config_path }}/cluster-autoscaler.kubeconfig"
      konnectivity-server-kubeconfig: "{{ apiserver_network_proxy_server_config_path }}/konnectivity-server.kubeconfig"
      kube-apiserver-kubeconfig: "/home/{{ kubectl_user }}/.kube/config"
      kube-controller-manager-kubeconfig: "{{ kube_controller_manager_config_path }}/kube-controller-manager.kubeconfig"
      kube-scheduler-kubeconfig: "{{ kube_scheduler_config_path }}/kube-scheduler.kubeconfig"
    ssl_exporter_certificates:
      konnectivity-server-certificates: "{{ apiserver_network_proxy_server_config_path }}/*.pem"
      kube-apiserver-certificates: "{{ kube_apiserver_config_path }}/*.pem"
      kube-controller-manager-certificates: "{{ kube_controller_manager_config_path }}/*.pem"
      kube-scheduler-certificates: "{{ kube_scheduler_config_path }}/*.pem"
  roles:
    - apt
    - sshd
    - systemd
    - vault
    - healthcheck
    - cilium_cli
    - wait_service
    - kubernetes_common
    - apiserver_network_proxy_server
    - etcd
    - kube_apiserver
    - kube_controller_manager
    - kube_scheduler
    - cluster_autoscaler
    - exoscale_cloud_controller_manager
    - kubectl
    - exoscale_cli
    - jq
    - ssl_exporter
    - node_exporter
