---

- name: Update base OS settings
  hosts: default
  become: true
  roles:
    - apt
    - sshd

- name: Install etcd and Vault agent
  hosts: default
  become: true
  vars:
    # vault agent
    vault_config_path: /etc/etcd
    vault_service_name: etcd-vault-agent
    vault_mode: agent
    vault_user: etcd
    vault_group: etcd
    # etcd healthcheck reverse-proxy for the Network Load Balancer
    healthcheck_port: 2378
    healthcheck_user: etcd
    healthcheck_script_path: "{{ etcd_bin_path }}/etcd-healthcheck"
    # etcd integration with vault agent
    vault_agent_exoscale_etcd_auth_path: auth/exoscale
    # backups
    rclone_backup_service_name: "etcd"
    rclone_backup_service_snapshot_commands:
      - "/bin/sh -c \". /etc/default/etcdctl && etcdctl defrag\""
      - "/bin/sh -c \". /etc/default/etcdctl && etcdctl snapshot save /var/backups/etcd/etcd.snapshot\""
    rclone_backup_path: /var/backups/etcd
    rclone_backup_user: "{{ etcd_user }}"
    rclone_backup_group: "{{ etcd_group }}"
    # monitoring
    ssl_exporter_certificates:
      etcd-certificates: "{{ etcd_certs_path }}/*.pem"
  roles:
    - systemd
    - vault
    - etcd
    - healthcheck
    - exoscale_cli
    - jq
    - exoscale_etcd
    - vault_agent_exoscale_etcd
    - rclone
    - rclone_backup
    - ssl_exporter
    - node_exporter
