---

- name: Update base OS settings
  hosts: default
  become: true
  vars:
  roles:
    - apt
    - sshd

- name: Install Vault server
  hosts: default
  become: true
  vars:
    vault_config_path: /etc/vault/server
    vault_tls_config_path: /var/vault/tls
    vault_external_plugins:
      - name: vault-plugin-auth-exoscale
        archive_url: https://github.com/exoscale/vault-plugin-auth-exoscale/releases/download/v0.2.0/vault-plugin-auth-exoscale_0.2.0_linux_amd64.tar.gz
        archive_checksum: 88df8ceb11624144b8ca13a127533866b7ec165b49a2362ad4ed793395edc204
        archive_item: vault-plugin-auth-exoscale
  roles:
    - systemd
    - vault

- name: Install Vault Agent
  hosts: default
  become: true
  vars:
    # vault agent
    vault_config_path: /etc/vault/agent
    vault_tls_config_path: /var/vault/tls
    vault_mode: agent
    # vault integration with vault agent
    vault_agent_vault_auth_path: auth/exoscale
    vault_agent_config_template: "{{ playbook_dir }}/defaults/templates/vault-agent-exoscale-vault.hcl.j2"
    vault_agent_approle_path: /var/vault
    vault_agent_secrets:
      kv_backup_encryption: "kv/platform/backup/vault-public"
      kv_backup_exoscale_api: "kv/platform/exoscale/vault-backup"
      pki_root: 'pki/root/cert/ca_chain'
      pki_vault_cert: 'pki/platform/vault/issue/server'
    # backups
    rclone_backup_service_extra_environment_files:
      - "/etc/default/vault-agent"
    rclone_backup_service_name: "vault"
    rclone_backup_service_snapshot_commands:
      - "/bin/sh -c \". /etc/default/vault && vault operator raft snapshot save /var/backups/vault/vault.snapshot\""
    rclone_backup_path: /var/backups/vault
    rclone_backup_user: "{{ vault_user }}"
    rclone_backup_group: "{{ vault_group }}"
    # monitoring
    ssl_exporter_certificates:
      vault-certificates: "{{ vault_tls_config_path }}/*.pem"
  roles:
    - systemd
    - vault
    - rclone
    - rclone_backup
    - ssl_exporter
    - node_exporter
