---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: $cert-manager:wildcard_name$-wildcard
  namespace: $ingress:namespace$
spec:
  secretName: $cert-manager:wildcard_name$-wildcard-cert
  duration: "2160h0m0s"
  renewBefore: "1440h0m0s"
  issuerRef:
    name: dns01-issuer-$ingress:class_suffix$
    kind: ClusterIssuer
  commonName: "*.$ingress:domain$"
  dnsNames:
    - "*.$ingress:domain$"
