---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: external-dns
  namespace: $external-dns:namespace$
  labels:
    app: external-dns
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: external-dns