---

# Package variables
# extracted from eu.gcr.io/k8s-artifacts-prod/kas-network-proxy/proxy-server:v0.0.33
konnectivity_server_binary: "proxy-server-v0.0.33-linux-amd64"

# Paths
konnectivity_server_bin_path: /usr/local/bin
konnectivity_server_config_path: /etc/kubernetes/konnectivity-server

# System user and group
konnectivity_user: kube
konnectivity_group: kube
konnectivity_groups: null
