apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://raw.githubusercontent.com/stakater/Reloader/v0.0.124/deployments/kubernetes/reloader.yaml
- ./pod-disruption-budget.yaml

namespace: reloader

patches:
- target:
    kind: ClusterRoleBinding
  patch: |-
    - op: remove
      path: /metadata/namespace
- target:
    kind: ClusterRole
  patch: |-
    - op: remove
      path: /metadata/namespace
- target:
    kind: .*
    name: .*
  patch: |-
    - op: replace
      path: /metadata/name
      value: reloader
    - op: remove
      path: /metadata/annotations
    - op: replace
      path: /metadata/labels
      value:
        app: reloader
- target:
    kind: Deployment
    name: reloader-reloader
  patch: |-
    - op: replace
      path: /spec/selector/matchLabels
      value:
        app: reloader
    - op: replace
      path: /spec/template/metadata/labels
      value:
        app: reloader
        rule.{{ .Values.platform.domain }}/allow-egress-api-server: "true"
    - op: replace
      path: /spec/template/spec/containers/0/name
      value: reloader
    - op: add
      path: /spec/template/spec/affinity
      value:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                app: reloader
    - op: add
      path: /spec/template/spec/containers/0/securityContext
      value:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 65534
        capabilities:
          drop:
          - ALL
    - op: add
      path: /spec/replicas
      value: 2
    - op: add
      path: /spec/template/spec/containers/0/resources
      value: 
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 10m
          memory: 32Mi