apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: '{{ .Values.platform.ingress.name }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns-{{ .Values.platform.ingress.name }}
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - pods
  - services
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-{{ .Values.platform.ingress.name }}-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns-{{ .Values.platform.ingress.name }}
subjects:
- kind: ServiceAccount
  name: external-dns
  namespace: '{{ .Values.platform.ingress.name }}'
---
apiVersion: v1
data:
  api-token: '{{ .Values.platform.ingress.cloudflare.apiToken |b64enc }}'
kind: Secret
metadata:
  name: '{{ .Values.platform.ingress.name }}-cloudflare-api-token'
  namespace: '{{ .Values.platform.ingress.name }}'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: '{{ .Values.platform.ingress.name }}'
spec:
  replicas: 2
  selector:
    matchLabels:
      app: external-dns
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns
        rule.{{ .Values.platform.domain }}/allow-egress-api-server: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: external-dns
            topologyKey: kubernetes.io/hostname
      containers:
      - args:
        - --source=ingress
        - --domain-filter={{ .Values.platform.ingress.domain }}
        - --provider=cloudflare
        env:
        - name: CF_API_TOKEN
          valueFrom:
            secretKeyRef:
              key: api-token
              name: '{{ .Values.platform.ingress.name }}-cloudflare-api-token'
        image: registry.k8s.io/external-dns/external-dns:v0.13.2
        name: external-dns
        resources:
          limits:
            cpu: 100m
            memory: 32Mi
          requests:
            cpu: 10m
            memory: 16Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 1000
          runAsNonRoot: true
          runAsUser: 1000
      serviceAccountName: external-dns
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    app: external-dns
  name: external-dns
  namespace: '{{ .Values.platform.ingress.name }}'
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: external-dns
