patches:
- target:
    kind: Deployment
    name: cilium-operator
  patch: |-
    - op: remove
      path: /spec/template/metadata/annotations
    - op: add
      path: /spec/template/metadata/labels/rule.{{ .Values.platform.domain }}~1allow-egress-api-server
      value: "true"
- target:
    kind: DaemonSet
    name: cilium
  patch: |-
    - op: add
      path: /spec/template/metadata/labels/rule.{{ .Values.platform.domain }}~1allow-egress-api-server
      value: "true"
- target:
    kind: Deployment
    name: hubble-relay
  patch: |-
    - op: remove
      path: /spec/template/metadata/annotations
    - op: add
      path: /spec/template/metadata/labels/rule.{{ .Values.platform.domain }}~1allow-egress-internal-dns
      value: "true"
    - op: add
      path: /spec/template/metadata/labels/rule.{{ .Values.platform.domain }}~1allow-egress-cilium-hubble
      value: "true"
    - op: add
      path: /spec/template/metadata/labels/rule.{{ .Values.platform.domain }}~1allow-egress-cilium-health
      value: "true"
# - target:
#     kind: Certificate
#     name: hubble-relay-client-certs
#   patch: |-
#     - op: replace
#       path: /spec/duration
#       value: 48h0m0s
# - target:
#     kind: Certificate
#     name: hubble-server-certs
#   patch: |-
#     - op: replace
#       path: /spec/duration
#       value: 48h0m0s

helmGlobals:
  chartHome: .helm
  configHome: .helm

helmCharts:
- name: cilium
  repo: https://helm.cilium.io/
  releaseName: cilium
  namespace: kube-system
  version: 1.13.0
  valuesInline:
    image:
      pullPolicy: Always

    resources:
      limits:
        memory: 512Mi
      requests:
        cpu: 50m
        memory: 192Mi

    cni:
      chainingMode: portmap

    containerRuntime:
      integration: containerd

    hostServices:
      enabled: true

    nodePort:
      enabled: true

    externalIPs:
      enabled: true

    hostPort:
      enabled: true

    k8sServiceHost: "{{ .Values.platform.kubernetes.apiserver.address }}"
    k8sServicePort: "6443"
    kubeProxyReplacement: strict

    hubble:
      enabled: true
      relay:
        enabled: true
        dialTimeout: 5s
        retryTimeout: 5s
      ui:
        enabled: true
      tls:
        enabled: false
        # auto:
        #   enabled: true
          # TODO: enable mTLS
          # method: certmanager
          # certManagerIssuerRef:
          #   group: "cert-manager.io"
          #   kind: "Issuer"
          #   name: "selfsigned-platform-core-cilium"

    ipam:
      operator:
        clusterPoolIPv4PodCIDR: "{{ .Values.platform.kubernetes.cluster.podCidrIPv4 }}"
        # clusterPoolIPv6PodCIDR: "{{ .Values.platform.kubernetes.cluster.podCidrIPv6 }}"

    ipv4:
      enabled: true

    ipv6:
      enabled: false # TODO: fix ipv6

    policyEnforcementMode: "always"
    policyAuditMode: true

    operator:
      image:
        pullPolicy: Always
      podDisruptionBudget:
        enabled: true
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: io.cilium/app
                operator: In
                values:
                - operator
            topologyKey: kubernetes.io/hostname
      resources:
        limits:
          cpu: 50m
          memory: 50Mi
        requests:
          cpu: 50m
          memory: 50Mi

    cgroup:
      hostRoot: /sys/fs/cgroup
      autoMount:
        enabled: false
