---

# Package variables
kubelet_version: "1.25.3"
kubelet_architecture_map:
  amd64: amd64
  x86_64: amd64
  aarch64: arm64

kubelet_architecture: "{{ kubelet_architecture_map[ansible_architecture] }}"
kubelet_os: "{{ ansible_system|lower }}"
kubelet_shasums: "kubelet.SHA256SUMS"
kubelet_url: "https://storage.googleapis.com/kubernetes-release/release/v{{ kubelet_version }}/bin/{{ kubelet_os }}/{{ kubelet_architecture }}/kubelet"
kubelet_checksum_file_url: "https://storage.googleapis.com/kubernetes-release/release/v{{ kubelet_version }}/SHA256SUMS"

# Paths
kubelet_bin_path: /usr/local/bin
kubelet_config_path: /etc/kubernetes/kubelet
