---

# Package variables
node_exporter_version: "1.3.1"
node_exporter_architecture_map:
  amd64: amd64
  x86_64: amd64
  aarch64: arm64

node_exporter_architecture: "{{ node_exporter_architecture_map[ansible_architecture] }}"
node_exporter_os: "{{ ansible_system|lower }}"
node_exporter_shasums: "node_exporter.SHA256SUMS"
node_exporter_pkg: "node_exporter-{{ node_exporter_version }}.{{ node_exporter_os }}-{{ node_exporter_architecture }}.tar.gz"
node_exporter_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.{{ node_exporter_os }}-{{ node_exporter_architecture }}.tar.gz"
node_exporter_checksum_file_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/sha256sums.txt"

# Paths
node_exporter_bin_path: /usr/local/bin
