---

- name: Vault template
  tags:
    - apiserver-network-proxy-server
  become: true
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ vault_config_path }}/{{ item }}"
    force: true
    owner: "{{ apiserver_network_proxy_server_user }}"
    group: "{{ apiserver_network_proxy_server_group }}"
    mode: "0622"
  loop:
    - apiserver-network-proxy.hcl

- name: systemd unit
  tags:
    - apiserver-network-proxy-server
  become: true
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
    force: true
    owner: root
    group: root
    mode: "0644"
  notify: reload systemd
  loop:
    - vault-apiserver-network-proxy-server.service
    - vault-apiserver-network-proxy-server.timer
