apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: http01-issuer-$ingress:class_suffix$
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: http01-issuer-$ingress:class_suffix$-account-key
    solvers:
    - http01:
        ingress:
          class: nginx-$ingress:class_suffix$
