---

- name: Add Kubernetes group
  tags:
    - konnectivity-server
  become: true
  ansible.builtin.group:
    name: "{{ konnectivity_group }}"
    state: present

- name: Add Kubernetes user
  tags:
    - konnectivity-server
  become: true
  ansible.builtin.user:
    name: "{{ konnectivity_user }}"
    comment: "Kubernetes user"
    group: "{{ konnectivity_group }}"
    groups: "{{ konnectivity_groups }}"
    shell: /bin/bash
    system: true

- name: "Copy proxy-server binary"
  tags:
    - konnectivity-server
  ansible.builtin.copy:
    src: "{{ konnectivity_server_binary }}"
    dest: "{{ konnectivity_server_bin_path }}/proxy-server"
    owner: "{{ konnectivity_user }}"
    group: "{{ konnectivity_group }}"
    mode: "0755"

- name: Create directories
  tags:
    - konnectivity-server
  become: true
  ansible.builtin.file:
    dest: "{{ item }}"
    state: directory
    owner: "{{ konnectivity_user }}"
    group: "{{ konnectivity_group }}"
    mode: 0755
  loop:
    - "{{ konnectivity_server_config_path }}"

- name: systemd unit
  tags:
    - konnectivity-server
  become: true
  ansible.builtin.template:
    src: "konnectivity.service.j2"
    dest: "/etc/systemd/system/konnectivity.service"
    force: true
    owner: root
    group: root
    mode: "0644"
  notify: reload systemd

- name: Add user to sudoers for service restart
  tags:
    - konnectivity-server
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/sudoers.d/konnectivity-server"
    line: "%{{ konnectivity_user }} ALL= NOPASSWD: /bin/systemctl restart konnectivity"
    owner: "root"
    group: "root"
    create: true
    mode: 0440

- name: konnectivity-server additional helper scripts
  tags:
    - konnectivity-server
  become: true
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ konnectivity_server_bin_path }}/{{ item }}"
    force: true
    owner: root
    group: root
    mode: "0777"
  loop:
    - konnectivity-server-launcher
