---

# issue: https://github.com/cilium/cilium/issues/10645
- name: Set sysctl configuration
  tags:
    - ciliun-sysctl
  become: true
  ansible.builtin.copy:
    src: "99-zzz-override_cilium.conf"
    dest: "/etc/sysctl.d/99-zzz-override_cilium.conf"
    force: true
    owner: root
    group: root
    mode: "0644"
