---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-$ingress:class_suffix$-secret
  namespace: $external-dns:namespace$
type: Opaque
stringData:
  api-token: $external-dns:cloudflare_token$