---

- name: Vault template
  tags:
    - cluster-autoscaler
  become: true
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ vault_config_path }}/{{ item }}"
    force: true
    owner: "{{ cluster_autoscaler_user }}"
    group: "{{ cluster_autoscaler_group }}"
    mode: "0622"
  loop:
    - exoscale-cluster-autoscaler.hcl

- name: systemd unit
  tags:
    - cluster-autoscaler
  become: true
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
    force: true
    owner: root
    group: root
    mode: "0644"
  notify: reload systemd
  loop:
    - vault-exoscale-cluster-autoscaler.service
    - vault-exoscale-cluster-autoscaler.timer
