---

- name: Check runc package signature file
  tags:
    - runc
  ansible.builtin.stat:
    path: "/tmp/{{ runc_signature }}"
  become: false
  register: runc_signature

- name: Get runc signature file
  tags:
    - runc
  ansible.builtin.get_url:
    url: "{{ runc_signature_file_url }}"
    dest: "/tmp/{{ runc_signature }}"
    owner: "root"
    group: "root"
    mode: "0666"
  when: not runc_signature.stat.exists | bool

- name: Check runc binary file
  tags:
    - runc
  ansible.builtin.stat:
    path: "{{ runc_bin_path }}/runc"
  become: false
  register: runc_binary

- name: "Download runc → {{ runc_url }}"
  tags:
    - runc
  ansible.builtin.get_url:
    url: "{{ runc_url }}"
    dest: "{{ runc_bin_path }}/runc"
    owner: "root"
    group: "root"
    mode: "0755"
    timeout: "42"
  when: not runc_binary.stat.exists | bool

# TODO: check GPG signature
# - name: Check signature
#   ansible.builtin.command: gpg --verify /tmp/{{ runc_signature }} {{ runc_bin_path }}/runc
