apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    app: kyverno
    app.kubernetes.io/component: kyverno
    app.kubernetes.io/instance: kyverno
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kyverno
    app.kubernetes.io/part-of: kyverno
    app.kubernetes.io/version: 2.6.1
    helm.sh/chart: kyverno-2.6.1
  name: kyverno
  namespace: kyverno
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: kyverno
      app.kubernetes.io/instance: kyverno
      app.kubernetes.io/name: kyverno
