---

- name: Set Exoscale Cloud Controller Manager group
  tags:
    - exoscale-cloud-controller-manager
  become: true
  ansible.builtin.group:
    name: "{{ exoscale_cloud_controller_manager_group }}"
    state: present

- name: Set Exoscale Cloud Controller Manager user
  tags:
    - exoscale-cloud-controller-manager
  become: true
  ansible.builtin.user:
    name: "{{ exoscale_cloud_controller_manager_user }}"
    comment: "Exoscale Cloud Controller Manager user"
    create_home: false
    group: "{{ exoscale_cloud_controller_manager_group }}"
    groups: "{{ exoscale_cloud_controller_manager_groups }}"
    shell: /bin/bash
    system: true

# Binary installation

- name: Install OS packages and Exoscale Cloud Controller Manager
  tags:
    - exoscale-cloud-controller-manager
  include_tasks: _install.yml

- name: Create configuration directory
  tags:
    - exoscale-cloud-controller-manager
  become: true
  ansible.builtin.file:
    dest: "{{ exoscale_cloud_controller_manager_config_path }}"
    state: directory
    owner: "{{ exoscale_cloud_controller_manager_user }}"
    group: "{{ exoscale_cloud_controller_manager_group }}"
    mode: 0770

- name: systemd unit
  tags:
    - exoscale-cloud-controller-manager
  become: true
  ansible.builtin.template:
    src: "{{ item }}.service.j2"
    dest: "/etc/systemd/system/{{ item }}.service"
    force: true
    owner: root
    group: root
    mode: "0644"
  notify: reload systemd
  loop:
    - exoscale-cloud-controller-manager
