---

- name: Set Exoscale Cloud Controller Manager group
  tags:
    - exoscale-cloud-controller-manager
  become: true
  ansible.builtin.group:
    name: "{{ exoscale_cloud_controller_manager_group }}"
    state: present

- name: Set Exoscale Cloud Controller Manager user
  tags:
    - exoscale-cloud-controller-manager
  become: true
  ansible.builtin.user:
    name: "{{ exoscale_cloud_controller_manager_user }}"
    comment: "Exoscale Cloud Controller Manager user"
    group: "{{ exoscale_cloud_controller_manager_group }}"
    groups: "{{ exoscale_cloud_controller_manager_groups }}"
    shell: /bin/bash
    system: true

# Binary installation

- name: Install OS packages and Exoscale Cloud Controller Manager
  tags:
    - exoscale-cloud-controller-manager
  include_tasks: _install.yml

- name: Create configuration directory
  tags:
    - exoscale-cloud-controller-manager
  become: true
  ansible.builtin.file:
    dest: "{{ exoscale_cloud_controller_manager_config_path }}"
    state: directory
    owner: "{{ exoscale_cloud_controller_manager_user }}"
    group: "{{ exoscale_cloud_controller_manager_group }}"
    mode: 0755

- name: Add user to sudoers for service restart
  tags:
    - exoscale-cloud-controller-manager
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/sudoers.d/cloud-controller-manager"
    line: "%{{ exoscale_cloud_controller_manager_user }} ALL= NOPASSWD: /bin/systemctl restart exoscale-cloud-controller-manager"
    owner: "root"
    group: "root"
    create: true
    mode: 0440

- name: controller manager additional helper scripts
  tags:
    - exoscale-cloud-controller-manager
  become: true
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ exoscale_cloud_controller_manager_bin_path }}/{{ item }}"
    force: true
    owner: root
    group: root
    mode: "0755"
  loop:
    - exoscale-cloud-controller-manager-launcher

- name: systemd unit
  tags:
    - exoscale-cloud-controller-manager
  become: true
  ansible.builtin.template:
    src: "exoscale-cloud-controller-manager.service.j2"
    dest: "/etc/systemd/system/exoscale-cloud-controller-manager.service"
    force: true
    owner: root
    group: root
    mode: "0644"
  notify: reload systemd
