---
apiVersion: v1
kind: Secret
metadata:
  name: metrics-server-ca
type: Opaque
data:
  kubelet-server-ca.pem: $kubernetes:kubelet_ca_cert$
  aggregationlayer-server-ca.pem: $kubernetes:aggregationlayer_ca_cert$