---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd
  namespace: argocd
spec:
  secretName: argocd-secret
  duration: 24h0m0s
  renewBefore: 18h0m0s
  subject:
    organizations:
      - argocd
  commonName: argocd.argocd.svc
  privateKey:
    rotationPolicy: Always
    algorithm: RSA
    size: 4096
  usages:
    - server auth
  dnsNames:
    - argocd.argocd.svc
    - "{{ .Values.platform.argocd.hostname }}"
  issuerRef:
    name: vault-platform-deployment-core
    kind: ClusterIssuer
    group: cert-manager.io
