resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.5.3/manifests/install.yaml
  - secret-oidc.yaml
  - certificate.yaml
  - ingress.yaml
  - https://raw.githubusercontent.com/argoproj-labs/argocd-vault-plugin/v1.13.0/manifests/cmp-sidecar/cmp-plugin.yaml

patchesStrategicMerge:
  - delete-dex.yaml
  - https://raw.githubusercontent.com/argoproj-labs/argocd-vault-plugin/v1.13.0/manifests/cmp-sidecar/argocd-repo-server.yaml

patches:
  - target:
      kind: Deployment
      name: argocd-server
    patch: |-
      - op: add
        path: /spec/template/metadata/labels/rule.{{ .Values.platform.domain }}~1allow-egress-api-server
        value: "true"
      - op: add
        path: /spec/template/metadata/labels/rule.{{ .Values.platform.domain }}~1allow-egress-dex
        value: "true"
  - target:
      kind: Deployment
      name: argocd-repo-server
    patch: |-
      - op: add
        path: /spec/template/metadata/labels/rule.{{ .Values.platform.domain }}~1allow-egress-internal-dns
        value: "true"
  - target:
      kind: StatefulSet
      name: argocd-application-controller
    patch: |-
      - op: add
        path: /spec/template/metadata/labels/rule.{{ .Values.platform.domain }}~1allow-egress-internal-dns
        value: "true"

  - target:
      kind: ClusterRole
      name: argocd-server
    patch: |-
      - op: add
        path: /rules/-
        value:
          apiGroups:
          - ""
          resources:
          - pods/exec
          verbs:
          - create
  - target:
      kind: ConfigMap
      name: argocd-cm
    patch: |-
      - op: add
        path: /data
        value:
          admin.enabled: "false"
          url: https://{{ .Values.platform.argocd.hostname }}
          oidc.config: |
            name: OIDC
            issuer: https://{{ .Values.platform.dex.hostname }}
            clientID: argocd
            clientSecret: $argocd-oidc-secret:oidc.dex.clientSecret

            requestedScopes: ["openid", "profile", "email", "groups"]
            requestedIDTokenClaims: {"groups": {"essential": true}}

            rootCA: |
              {{- .Values.platform.dex.caCert | nindent 6 }}
          exec.enabled: "true"
          resource.exclusions: |
            - apiGroups:
                - cilium.io
              kinds:
                - CiliumIdentity
                - CiliumEndpoint
              clusters:
                - "*"
  - target:
      kind: ConfigMap
      name: argocd-rbac-cm
    patch: |-
      - op: add
        path: /data
        value:
          policy.csv: |
            {{- .Values.platform.argocd.policy | nindent 4 }}

          policy.default: role:''
          scopes: "[email]"

namespace: argocd
