---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ingress-$ingress:class_suffix$-external-dns-cloudflare
  namespace: $external-dns:namespace$
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ingress-$ingress:class_suffix$-external-dns-cloudflare-tokenreview-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: ingress-$ingress:class_suffix$-external-dns-cloudflare
    namespace: $external-dns:namespace$
---
apiVersion: v1
kind: Secret
metadata:
  name: ingress-$ingress:class_suffix$-external-dns-cloudflare
  namespace: $external-dns:namespace$
  annotations:
    kubernetes.io/service-account.name: ingress-$ingress:class_suffix$-external-dns-cloudflare
type: "kubernetes.io/service-account-token"
---
apiVersion: v1
kind: Secret
metadata:
  name: ingress-$ingress:class_suffix$-vault-cloudflare
  namespace: $external-dns:namespace$
data:
  vault-ca-cert: $vault:cluster_ca_cert$
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: ingress-$ingress:class_suffix$-vault-cloudflare
  namespace: $external-dns:namespace$
spec:
  provider:
    vault:
      server: "$vault:cluster_addr$"
      caProvider:
        type: Secret
        name: ingress-$ingress:class_suffix$-vault-cloudflare
        key: vault-ca-cert
      path: "kv/platform/cloudflare"
      version: "v1"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "ingress-$ingress:class_suffix$-external-dns-cloudflare"
          secretRef:
            name: "ingress-$ingress:class_suffix$-external-dns-cloudflare"
            key: "token"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ingress-$ingress:class_suffix$-vault-cloudflare
  namespace: $external-dns:namespace$
spec:
  refreshInterval: "60s"
  secretStoreRef:
    name: ingress-$ingress:class_suffix$-vault-cloudflare
    kind: SecretStore
  target:
    name: ingress-$ingress:class_suffix$-cloudflare-api-token
  data:
  - secretKey: api-token
    remoteRef:
      key: $ingress:class_suffix$-external-dns-cloudflare
      property: api-key