---

- name: Add Kubernetes Controller Manager group
  tags:
    - kube-controller-manager
  become: true
  ansible.builtin.group:
    name: "{{ kube_controller_manager_group }}"
    state: present

- name: Add Kubernetes Controller Manager user
  tags:
    - kube-controller-manager
  become: true
  ansible.builtin.user:
    name: "{{ kube_controller_manager_user }}"
    comment: "Kubernetes Controller Manager user"
    group: "{{ kube_controller_manager_group }}"
    groups: "{{ kube_controller_manager_groups }}"
    shell: /bin/bash
    system: true

- name: Check Kubernetes Controller Manager checksum file
  tags:
    - kube-controller-manager
  ansible.builtin.stat:
    path: "/tmp/{{ kube_controller_manager_shasums }}"
  become: false
  register: kube_controller_manager_checksum

- name: Get Kubernetes Controller Manager checksum file
  tags:
    - kube-controller-manager
  ansible.builtin.get_url:
    url: "{{ kube_controller_manager_checksum_file_url }}"
    dest: "/tmp/{{ kube_controller_manager_shasums }}"
    owner: "{{ kube_controller_manager_user }}"
    group: "{{ kube_controller_manager_group }}"
    mode: "0666"
  when: not kube_controller_manager_checksum.stat.exists | bool

- name: Get Kubernetes Controller Manager checksum
  tags:
    - kube-controller-manager
    - skip_ansible_lint
  ansible.builtin.shell: |
    set -o pipefail
    grep "v{{ kube_controller_manager_version }}/bin/{{ kube_controller_manager_os }}/{{ kube_controller_manager_architecture }}/kube-controller-manager$" "/tmp/{{ kube_controller_manager_shasums }}" | awk '{print $1}'
  args:
    executable: /bin/bash
  changed_when: false
  become: false
  register: kube_controller_manager_sha256

- name: "Download Kubernetes Controller Manager → {{ kube_controller_manager_url }}"
  tags:
    - kube-controller-manager
  ansible.builtin.get_url:
    url: "{{ kube_controller_manager_url }}"
    dest: "{{ kube_controller_manager_bin_path }}/kube-controller-manager"
    checksum: "sha256:{{ kube_controller_manager_sha256.stdout }}"
    owner: "{{ kube_controller_manager_user }}"
    group: "{{ kube_controller_manager_group }}"
    mode: "0755"

- name: Create directories
  tags:
    - kube-controller-manager
  become: true
  ansible.builtin.file:
    dest: "{{ item }}"
    state: directory
    owner: "{{ kube_controller_manager_user }}"
    group: "{{ kube_controller_manager_group }}"
    mode: 0755
  loop:
    - "{{ kube_controller_manager_config_path }}"

- name: systemd unit
  tags:
    - kube-controller-manager
  become: true
  ansible.builtin.template:
    src: "kube-controller-manager.service.j2"
    dest: "/etc/systemd/system/kube-controller-manager.service"
    force: true
    owner: root
    group: root
    mode: "0644"
  notify: reload systemd

- name: Add user to sudoers for service restart
  tags:
    - kube-controller-manager
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/sudoers.d/kube-controller-manager"
    line: "%{{ kube_controller_manager_user }} ALL= NOPASSWD: /bin/systemctl restart kube-controller-manager"
    owner: "root"
    group: "root"
    create: true
    mode: 0440

- name: controller manager additional helper scripts
  tags:
    - kube-controller-manager
  become: true
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ kube_controller_manager_bin_path }}/{{ item }}"
    force: true
    owner: root
    group: root
    mode: "0755"
  loop:
    - kube-controller-manager-launcher
