---

- name: Update APT settings
  include_tasks: _apt_settings.yml

- name: Remove unwanted packages
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: absent
    purge: true
  loop: "{{ apt_unwanted_packages }}"

- name: Add wanted packages
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ apt_wanted_packages }}"

- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: true
