---

- name: Add Kubernetes client group
  tags:
    - kubectl
  become: true
  group:
    name: "{{ kubectl_group }}"
    state: present

- name: Add Kubernetes client user
  tags:
    - kubectl
  become: true
  user:
    name: "{{ kubectl_user }}"
    comment: "Kubernetes client user"
    group: "{{ kubectl_group }}"
    groups: "{{ kubectl_groups }}"
    shell: /bin/bash
    system: true

- name: Check kubectl checksum file
  tags:
    - kubectl
  stat:
    path: "/tmp/{{ kubectl_shasums }}"
  become: false
  register: kubectl_checksum

- name: Get kubectl checksum file
  tags:
    - kubectl
  get_url:
    url: "{{ kubectl_checksum_file_url }}"
    dest: "/tmp/{{ kubectl_shasums }}"
  when: not kubectl_checksum.stat.exists | bool

- name: Get kubectl checksum
  tags:
    - kubectl
    - skip_ansible_lint
  shell: |
    set -o pipefail
    grep "v{{ kubectl_version }}/bin/{{ kubectl_os }}/{{ kubectl_architecture }}/kubectl$" "/tmp/{{ kubectl_shasums }}" | awk '{print $1}'
  args:
    executable: /bin/bash
  changed_when: false
  become: false
  register: kubectl_sha256

- name: "Download kubectl → {{ kubectl_url }}"
  tags:
    - kubectl
  get_url:
    url: "{{ kubectl_url }}"
    dest: "{{ kubectl_bin_path }}/kubectl"
    checksum: "sha256:{{ kubectl_sha256.stdout }}"
    owner: "root"
    group: "root"
    mode: "0755"

- name: Create directories
  tags:
    - kubectl
  become: true
  file:
    dest: "{{ item }}"
    state: directory
    owner: "{{ kubectl_user }}"
    group: "{{ kubectl_group }}"
    mode: 0755
  loop:
    - "{{ kubectl_config_path }}"
    - "/home/{{ kubectl_user }}/.kube"
