apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: http01-{{ .Values.platform.ingress.name }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: http01-issuer-{{ .Values.platform.ingress.name }}-account-key
    solvers:
    - http01:
        ingress:
          class: nginx-{{ .Values.platform.ingress.name }}
