apiVersion: v1
data:
  config.yaml: |
    issuer: ${ oidc_provider_url }

    storage:
      type: kubernetes
      config:
        inCluster: true

    loger:
      level: debug

    web:
      http: 0.0.0.0:5556
      # tlsCert: /etc/dex/tls/tls.crt
      # tlsKey: /etc/dex/tls/tls.key

    oauth2:
      skipApprovalScreen: true

    connectors:
    - type: oidc
      id: oidc
      name: Default OIDC provider
      config:
        issuer: "${ oidc_issuer }"

        clientID: "${ oidc_client_id }"
        clientSecret: "${ oidc_client_secret }"

        redirectURI: ${ oidc_provider_url }/callback

        scopes:
        - user
        - groups
        userNameKey: username

        insecureEnableGroups: true

    staticClients:
      - id: kubectl
        name: Kubernetes CLI
        secret: kubectl-secret
        redirectURIs:
        - http://localhost:8000
        - http://localhost:8080/oauth2/callback

# kubectl oidc-login setup --oidc-issuer-url=https://dex.platform.i6h.io --oidc-client-id=kubectl

kind: ConfigMap
metadata:
  name: dex
  namespace: dex