---
apiVersion: v1
kind: Secret
metadata:
  name: metrics-server-ca
type: Opaque
data:
  kubelet-server-ca.pem: ${ kubernetes_kubelet_ca_cert }
  aggregationlayer-server-ca.pem: ${ kubernetes_aggregationlayer_ca_cert }