image:
  pullPolicy: Always

resources:
  limits:
    memory: 512Mi
  requests:
    cpu: 50m
    memory: 192Mi

cni:
  chainingMode: portmap

containerRuntime:
  integration: containerd

hostServices:
  enabled: true

k8sServiceHost: "$kubernetes:apiserver_ipv4$"
k8sServicePort: "6443"
kubeProxyReplacement: strict

hubble:
  enabled: false

ipam:
  operator:
    clusterPoolIPv4PodCIDR: "$kubernetes:pod_cidr_ipv4$"
    clusterPoolIPv6PodCIDR: "$kubernetes:pod_cidr_ipv6$"

ipv6:
  enabled: true

operator:
  image:
    pullPolicy: Always
  # TODO: As of v1.11.4, this settings is available in default settings.yaml but is not taken into account,
  # So we have to inject the PDB manifest ourself, to allow the cluster autoscaler to work properly
  #
  # podDisruptionBudget:
  #   enabled: true
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: io.cilium/app
            operator: In
            values:
            - operator
        topologyKey: kubernetes.io/hostname
  resources:
    limits:
      cpu: 50m
      memory: 50Mi
    requests:
      cpu: 50m
      memory: 50Mi
