---

- name: Check stargz-snapshotter package checksum file
  tags:
    - stargz-snapshotter
  ansible.builtin.stat:
    path: "/tmp/{{ stargz_snapshotter_shasums }}"
  become: false
  register: stargz_snapshotter_checksum

- name: Get stargz-snapshotter package checksum file
  tags:
    - stargz-snapshotter
  ansible.builtin.get_url:
    url: "{{ stargz_snapshotter_checksum_file_url }}"
    dest: "/tmp/{{ stargz_snapshotter_shasums }}"
    owner: root
    group: root
    mode: "0666"
  when: not stargz_snapshotter_checksum.stat.exists | bool

- name: Get stargz-snapshotter package checksum
  tags:
    - stargz-snapshotter
    - skip_ansible_lint
  ansible.builtin.shell: |
    set -o pipefail
    grep "{{ stargz_snapshotter_pkg }}" "/tmp/{{ stargz_snapshotter_shasums }}" | awk '{print $1}'
  args:
    executable: /bin/bash
  changed_when: false
  become: false
  register: stargz_snapshotter_sha256

- name: Check stargz-snapshotter package file
  tags:
    - stargz-snapshotter
  ansible.builtin.stat:
    path: "/tmp/{{ stargz_snapshotter_pkg }}"
  become: false
  register: stargz_snapshotter_package

- name: "Download stargz-snapshotter → {{ stargz_snapshotter_tgz_url }}"
  tags:
    - stargz-snapshotter
  ansible.builtin.get_url:
    url: "{{ stargz_snapshotter_tgz_url }}"
    dest: "/tmp/{{ stargz_snapshotter_pkg }}"
    owner: root
    group: root
    mode: "0666"
    checksum: "sha256:{{ stargz_snapshotter_sha256.stdout }}"
    timeout: "42"
  when: not stargz_snapshotter_package.stat.exists | bool

- name: Unarchive stargz-snapshotter
  tags:
    - stargz-snapshotter
  ansible.builtin.unarchive:
    remote_src: true
    src: "/tmp/{{ stargz_snapshotter_pkg }}"
    dest: "/tmp"
    creates: "/tmp/{{ item }}"
  loop: "{{ stargz_snapshotter_binaries }}"

- name: Install stargz-snapshotter
  tags:
    - stargz-snapshotter
  become: true
  ansible.builtin.copy:
    remote_src: true
    src: "/tmp/{{ item }}"
    dest: "{{ stargz_snapshotter_bin_path }}"
    owner: "root"
    group: "root"
    mode: "0755"
  loop: "{{ stargz_snapshotter_binaries }}"

- name: systemd unit
  tags:
    - stargz-snapshotter
  become: true
  ansible.builtin.template:
    src: "stargz-snapshotter.service.j2"
    dest: "/etc/systemd/system/stargz-snapshotter.service"
    force: true
    owner: root
    group: root
    mode: "0644"
  notify:
    - reload systemd
    - enable stargz-snapshotter
