---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: platform-kubernetes-metrics-server
spec:
  vault:
    path: $vault:path_pki_sign:aggregation_layer$
    server: $vault:cluster_addr$
    caBundle: $vault:cluster_ca_cert$
    auth:
      kubernetes:
        role: metrics-server
        mountPath: /v1/auth/kubernetes/cert-manager/
        secretRef:
          name: metrics-server-vault-issuer
          key: token