apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: metrics-server
  name: metrics-server
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    k8s-app: metrics-server
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: system:aggregated-metrics-reader
rules:
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  - nodes
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    k8s-app: metrics-server
  name: system:metrics-server
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  - nodes/stats
  - namespaces
  - configmaps
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    k8s-app: metrics-server
  name: metrics-server-auth-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: metrics-server
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    k8s-app: metrics-server
  name: metrics-server:system:auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: metrics-server
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    k8s-app: metrics-server
  name: system:metrics-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:metrics-server
subjects:
- kind: ServiceAccount
  name: metrics-server
  namespace: kube-system
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: metrics-server
  name: metrics-server
  namespace: kube-system
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    k8s-app: metrics-server
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: metrics-server
  namespace: kube-system
  labels:
    k8s-app: metrics-server
spec:
  minAvailable: 1
  selector:
    matchLabels:
      k8s-app: metrics-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: metrics-server
  name: metrics-server
  namespace: kube-system
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: metrics-server
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        k8s-app: metrics-server
    spec:
      containers:
      - args:
        - --kubelet-certificate-authority=/var/run/secrets/platform/ca/kubelet-server-ca.pem
        - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
        - --kubelet-use-node-status-port
        - --metric-resolution=15s
        - --requestheader-client-ca-file=/var/run/secrets/platform/cert/ca.crt
        - --tls-cert-file=/var/run/secrets/platform/cert/tls.crt
        - --tls-private-key-file=/var/run/secrets/platform/cert/tls.key
        - --secure-port=4443
        image: k8s.gcr.io/metrics-server/metrics-server:v0.5.2
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /livez
            port: https
            scheme: HTTPS
          periodSeconds: 10
        name: metrics-server
        ports:
        - containerPort: 4443
          name: https
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: https
            scheme: HTTPS
          initialDelaySeconds: 20
          periodSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 50Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
        volumeMounts:
          - name: ca
            mountPath: /var/run/secrets/platform/ca
          - name: cert
            mountPath: /var/run/secrets/platform/cert
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                k8s-app: metrics-server
      nodeSelector:
        kubernetes.io/os: linux
      volumes:
      - name: ca
        secret:
          secretName: metrics-server-ca
      - name: cert
        secret:
          secretName: metrics-server-cert
      priorityClassName: system-cluster-critical
      serviceAccountName: metrics-server
---
apiVersion: v1
kind: Secret
metadata:
  name: metrics-server-ca
type: Opaque
data:
  kubelet-server-ca.pem: $kubernetes:kubelet_ca_cert$
  aggregationlayer-server-ca.pem: $kubernetes:aggregationlayer_ca_cert$
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  labels:
    k8s-app: metrics-server
  name: v1beta1.metrics.k8s.io
spec:
  group: metrics.k8s.io
  groupPriorityMinimum: 100
  insecureSkipTLSVerify: false
  caBundle: $kubernetes:aggregationlayer_ca_cert$
  service:
    name: metrics-server
    namespace: kube-system
  version: v1beta1
  versionPriority: 100
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: platform-kubernetes-metrics-server
spec:
  vault:
    path: $vault:path_pki_sign:aggregation_layer$
    server: $vault:cluster_addr$
    caBundle: $vault:cluster_ca_cert$
    auth:
      kubernetes:
        role: metrics-server
        mountPath: /v1/auth/kubernetes/cert-manager/
        secretRef:
          name: metrics-server-vault-issuer
          key: token
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: metrics-server
spec:
  secretName: metrics-server-cert
  duration: 24h
  renewBefore: 18h
  subject:
    organizations:
      - metrics-server
  commonName: metrics-server.kube-system.svc
  isCA: false
  privateKey:
    rotationPolicy: Always
    algorithm: RSA
    size: 4096
  usages:
    - server auth
  dnsNames:
    - metrics-server.kube-system.svc
  issuerRef:
    name: platform-kubernetes-metrics-server
    kind: Issuer
    group: cert-manager.io
