apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/stakater/Reloader/v0.0.113/deployments/kubernetes/manifests/clusterrole.yaml
  - https://raw.githubusercontent.com/stakater/Reloader/v0.0.113/deployments/kubernetes/manifests/clusterrolebinding.yaml
  - https://raw.githubusercontent.com/stakater/Reloader/v0.0.113/deployments/kubernetes/manifests/role.yaml
  - https://raw.githubusercontent.com/stakater/Reloader/v0.0.113/deployments/kubernetes/manifests/rolebinding.yaml
  - https://raw.githubusercontent.com/stakater/Reloader/v0.0.113/deployments/kubernetes/manifests/serviceaccount.yaml
  - https://raw.githubusercontent.com/stakater/Reloader/v0.0.113/deployments/kubernetes/manifests/deployment.yaml

namespace: reloader

patches:
- target:
    kind: .*
    name: .*
  patch: |-
    - op: replace
      path: /metadata/name
      value: reloader
    - op: remove
      path: /metadata/annotations
    - op: replace
      path: /metadata/labels
      value:
        app: reloader
- target:
    kind: Deployment
    name: reloader-reloader
  patch: |-
    - op: replace
      path: /spec/selector/matchLabels
      value:
        app: reloader
    - op: replace
      path: /spec/template/metadata/labels
      value:
        app: reloader
    - op: replace
      path: /spec/template/spec/containers/0/name
      value: reloader