---

# Package variables
crictl_version: "1.24.0"
crictl_architecture_map:
  amd64: amd64
  x86_64: amd64
  aarch64: arm64

crictl_architecture: "{{ crictl_architecture_map[ansible_architecture] }}"
crictl_os: "{{ ansible_system|lower }}"
crictl_pkg: "crictl-v{{ crictl_version }}-{{ crictl_os }}-{{ crictl_architecture }}.tar.gz"
crictl_shasums: "crictl-v{{ crictl_version }}-{{ crictl_os }}-{{ crictl_architecture }}.tar.gz.sha256"
crictl_tgz_url: "https://github.com/kubernetes-sigs/cri-tools/releases/download/v{{ crictl_version }}/crictl-v{{ crictl_version }}-{{ crictl_os }}-{{ crictl_architecture }}.tar.gz"
crictl_checksum_file_url: "https://github.com/kubernetes-sigs/cri-tools/releases/download/v{{ crictl_version }}/crictl-v{{ crictl_version }}-{{ crictl_os }}-{{ crictl_architecture }}.tar.gz.sha256"

# Paths
crictl_bin_path: /usr/local/bin
