---

- name: systemd unit
  tags:
    - vault
  become: true
  ansible.builtin.template:
    src: "vault.service.j2"
    dest: "/etc/systemd/system/{{ vault_service_name }}.service"
    force: true
    owner: root
    group: root
    mode: "0644"
  notify: reload systemd
