- name: Create a fresh Vault snapshot
  become: true
  become_user: "{{ vault_user }}"
  ansible.builtin.shell: |
    vault operator raft snapshot save /home/{{ vault_user }}/vault.snapshot
  environment:
    VAULT_AGENT_ADDR: unix://{{ vault_agent_socket_path }}

- name: Retrieve the snapshot locally
  become: true
  ansible.builtin.fetch:
    src: "/home/{{ vault_user }}/vault.snapshot"
    dest: "../artifacts/latest-vault.snapshot"
    flat: true