helmGlobals:
  chartHome: .helm
  configHome: .helm

helmCharts:
- name: cert-manager
  repo: https://charts.jetstack.io
  releaseName: cert-manager
  namespace: cert-manager
  version: 1.6.0
  valuesInline:
    installCRDs: true
    global:
      leaderElection:
        namespace: cert-manager