---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-deployment-core
  namespace: cert-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-deployment-core-tokenreview-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: cert-manager-deployment-core
    namespace: cert-manager
---
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-deployment-core-token
  namespace: cert-manager
  annotations:
    kubernetes.io/service-account.name: cert-manager-deployment-core
type: "kubernetes.io/service-account-token"
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-platform-deployment-core
spec:
  vault:
    path: "{{ .Values.platform.vault.corePKISignPath }}"
    server: "{{ .Values.platform.vault.baseUrl }}"
    caBundle: "{{ .Values.platform.vault.caCert | b64enc }}"
    auth:
      kubernetes:
        role: certificate-core
        mountPath: /v1/auth/kubernetes/
        secretRef:
          name: cert-manager-deployment-core-token
          key: token