---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cert-manager-webhook
  namespace: cert-manager
  labels:
    app: webhook
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: webhook