---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cert-manager
  namespace: cert-manager
  labels:
    app: cert-manager
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: cert-manager