---

- name: systemd unit
  tags:
    - vault
  become: true
  template:
    src: "vault.service.j2"
    dest: "/etc/systemd/system/vault-{{ vault_mode }}.service"
    force: true
    owner: root
    group: root
    mode: "0644"
  notify: reload systemd
