---

- name: Insert http(s) export in dotfile
  tags:
    - vault
  become: true
  lineinfile:
    path: "{{ vault_home }}/{{ vault_dotfile }}"
    regexp: "^export VAULT_ADDR="
    line: "export VAULT_ADDR='https://127.0.0.1:{{ vault_port }}'"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    create: true
    mode: 0600
  when:
    - not vault_dotfile_disable

- name: Insert CA cert export in dotfile
  tags:
    - vault
  become: true
  lineinfile:
    path: "{{ vault_home }}/{{ vault_dotfile }}"
    regexp: "^export VAULT_CACERT="
    line: "export VAULT_CACERT={{ vault_tls_config_path }}/{{ vault_tls_ca_cert_file }}"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    create: true
    mode: 0600
  when:
    - not vault_dotfile_disable

- name: Insert Client cert export in dotfile
  tags:
    - vault
  become: true
  lineinfile:
    path: "{{ vault_home }}/{{ vault_dotfile }}"
    regexp: "^export VAULT_CLIENT_CERT="
    line: "export VAULT_CLIENT_CERT={{ vault_tls_config_path }}/{{ vault_backend_tls_cert_file }}"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    create: true
    mode: 0600
  when:
    - not vault_dotfile_disable

- name: Insert Client key export in dotfile
  tags:
    - vault
  become: true
  lineinfile:
    path: "{{ vault_home }}/{{ vault_dotfile }}"
    regexp: "^export VAULT_CLIENT_KEY="
    line: "export VAULT_CLIENT_KEY={{ vault_tls_config_path }}/{{ vault_backend_tls_key_file }}"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    create: true
    mode: 0600
  when:
    - not vault_dotfile_disable
