---

- name: Check Kubelet checksum file
  tags:
    - kubelet
  ansible.builtin.stat:
    path: "/tmp/{{ kubelet_shasums }}"
  become: false
  register: kubelet_checksum

- name: Get Kubelet checksum file
  tags:
    - kubelet
  ansible.builtin.get_url:
    url: "{{ kubelet_checksum_file_url }}"
    dest: "/tmp/{{ kubelet_shasums }}"
    owner: "root"
    group: "root"
    mode: "0666"
  when: not kubelet_checksum.stat.exists | bool

- name: Get Kubelet checksum
  tags:
    - kubelet
    - skip_ansible_lint
  ansible.builtin.shell: |
    set -o pipefail
    grep "v{{ kubelet_version }}/bin/{{ kubelet_os }}/{{ kubelet_architecture }}/kubelet$" "/tmp/{{ kubelet_shasums }}" | awk '{print $1}'
  args:
    executable: /bin/bash
  changed_when: false
  become: false
  register: kubelet_sha256

- name: "Download Kubelet → {{ kubelet_url }}"
  tags:
    - kubelet
  ansible.builtin.get_url:
    url: "{{ kubelet_url }}"
    dest: "{{ kubelet_bin_path }}/kubelet"
    checksum: "sha256:{{ kubelet_sha256.stdout }}"
    owner: "root"
    group: "root"
    mode: "0755"

- name: Create directories
  tags:
    - kubelet
  become: true
  ansible.builtin.file:
    dest: "{{ item }}"
    state: directory
    owner: "root"
    group: "root"
    mode: 0700
  loop:
    - "{{ kubelet_config_path }}"

- name: systemd unit
  tags:
    - kubelet
  become: true
  ansible.builtin.template:
    src: "kubelet.service.j2"
    dest: "/etc/systemd/system/kubelet.service"
    force: true
    owner: root
    group: root
    mode: "0644"
  notify: reload systemd

- name: kubelet additional helper scripts
  tags:
    - kubelet
  become: true
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ kubelet_bin_path }}/{{ item }}"
    force: true
    owner: root
    group: root
    mode: "0755"
  loop:
    - kubelet-launcher
