---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: reloader
  namespace: reloader
  labels:
    app: reloader
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: reloader