---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-deployment-core
  namespace: cert-manager
---
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-deployment-core-token
  namespace: cert-manager
  annotations:
    kubernetes.io/service-account.name: cert-manager-deployment-core
type: "kubernetes.io/service-account-token"
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-platform-deployment-core
spec:
  vault:
    path: ${ vault_path_pki_sign_deployment["core"] }
    server: ${ vault_cluster_url }
    caBundle: ${ vault_cluster_ca_cert }
    auth:
      kubernetes:
        role: certificate-core
        mountPath: /v1/auth/kubernetes/
        secretRef:
          name: cert-manager-deployment-core-token
          key: token