---
apiVersion: v1
kind: Secret
metadata:
  name: metrics-server-ca
type: Opaque
data:
  kubelet-server-ca.pem: "{{ .Values.platform.kubernetes.kubelet.caCert | b64enc }}"
  aggregationlayer-server-ca.pem: "{{ .Values.platform.kubernetes.aggregationLayer.caCert | b64enc }}"