---

- name: Install nginx
  tags:
    - healthcheck
  become: true
  package:
    name: ['nginx', 'fcgiwrap']
    state: present
    update_cache: true

- name: Set healthcheck endpoint configuration
  tags:
    - healthcheck
  template:
    src: "default.j2"
    dest: "/etc/nginx/sites-available/default"
    force: true
    owner: root
    group: root
    mode: "0644"

- name: Change fcgiwrap user
  tags:
    - healthcheck
  replace:
    path: /lib/systemd/system/fcgiwrap.service
    regexp: "^User=([a-zA-Z0-9_-]+)$"
    replace: "User={{ healthcheck_user }}"

- name: Change fcgiwrap group
  tags:
    - healthcheck
  replace:
    path: /lib/systemd/system/fcgiwrap.service
    regexp: "^Group=([a-zA-Z0-9_-]+)$"
    replace: "Group={{ healthcheck_user }}"
