---
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: allow-egress-konnectivity-server
spec:
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - matchLabels:
            rule.{{ .Values.platform.domain }}/allow-egress-konnectivity-server: "true"
  egress:
    - toEntities:
      - kube-apiserver
      toPorts:
        - ports:
            - port: "8091"
              protocol: TCP
