---
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: allow-egress-hubble
spec:
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - matchLabels:
            rule.{{ .Values.platform.domain }}/allow-egress-cilium-hubble: "true"
  egress:
    - toEntities:
      - remote-node
      - host
      toPorts:
        - ports:
            - port: "4244"
              protocol: TCP
