---
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: allow-egress-kubelet
spec:
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - matchLabels:
            rule.{{ .Values.platform.domain }}/allow-egress-kubelet: "true"
  egress:
    - toEntities:
      - remote-node
      - host
      toPorts:
        - ports:
            - port: "10250"
              protocol: TCP
