---
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: allow-egress-dex
spec:
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - matchLabels:
            rule.{{ .Values.platform.domain }}/allow-egress-dex: "true"
  egress:
    - toCIDR:
      - "{{ .Values.platform.vault.publicIP }}/32"
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
