---
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: allow-egress-dns
spec:
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - matchLabels:
            rule.{{ .Values.platform.domain }}/allow-egress-dns: "true"
  egress:
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"
