---
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: allow-egress-api-server
spec:
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - matchLabels:
            rule.{{ .Values.platform.domain }}/allow-egress-api-server: "true"
  egress:
    - toServices:
        - k8sService:
            serviceName: kubernetes
            namespace: default
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
    - toEntities:
      - kube-apiserver
      toPorts:
        - ports:
            - port: "6443"
              protocol: TCP
