apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  externalTrafficPolicy: Local
  externalIPs:
  - "{{ .Values.platform.ingress.loadbalancerIP }}"