---

# Package variables
kube_controller_manager_version: "1.27.3"
kube_controller_manager_architecture_map:
  amd64: amd64
  x86_64: amd64
  aarch64: arm64

kube_controller_manager_architecture: "{{ kube_controller_manager_architecture_map[ansible_architecture] }}"
kube_controller_manager_os: "{{ ansible_system|lower }}"
kube_controller_manager_shasums: "controllermanager.SHA256SUMS"
kube_controller_manager_url: "https://storage.googleapis.com/kubernetes-release/release/v{{ kube_controller_manager_version }}/bin/{{ kube_controller_manager_os }}/{{ kube_controller_manager_architecture }}/kube-controller-manager"
kube_controller_manager_checksum_file_url: "https://storage.googleapis.com/kubernetes-release/release/v{{ kube_controller_manager_version }}/SHA256SUMS"

# Paths
kube_controller_manager_bin_path: /usr/local/bin
kube_controller_manager_config_path: /var/kubernetes/controller-manager

# System user and group
kube_controller_manager_user: kube-controller-manager
kube_controller_manager_group: kubernetes
kube_controller_manager_groups: null
