apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: platform-kubernetes-metrics-server
  namespace: kube-system
spec:
  vault:
    path: $vault:path_pki_sign:aggregation_layer$
    server: $vault:cluster_addr$
    caBundle: $vault:cluster_ca_cert$
    auth:
      kubernetes:
        role: metrics-server
        mountPath: /v1/auth/kubernetes/cert-manager/
        secretRef:
          name: cert-manager-metrics-server-token
          key: token
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  secretName: metrics-server-cert
  duration: 24h0m0s
  renewBefore: 18h0m0s
  subject:
    organizations:
      - metrics-server
  commonName: metrics-server.kube-system.svc
  privateKey:
    rotationPolicy: Always
    algorithm: RSA
    size: 4096
  usages:
    - server auth
  dnsNames:
    - metrics-server.kube-system.svc
  issuerRef:
    name: platform-kubernetes-metrics-server
    kind: Issuer
    group: cert-manager.io
