---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-metrics-server
  namespace: kube-system
---
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-metrics-server-token
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: cert-manager-metrics-server
type: "kubernetes.io/service-account-token"
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: platform-deployment-metrics-server
  namespace: kube-system
spec:
  vault:
    path: ${ vault_path_pki_sign_aggregation_layer }
    server: ${ vault_cluster_url }
    caBundle: ${ vault_cluster_ca_cert }
    auth:
      kubernetes:
        role: certificate-metrics-server
        mountPath: /v1/auth/kubernetes/
        secretRef:
          name: cert-manager-metrics-server-token
          key: token
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  secretName: metrics-server-cert
  duration: 24h0m0s
  renewBefore: 18h0m0s
  subject:
    organizations:
      - metrics-server
  commonName: metrics-server.kube-system.svc
  privateKey:
    rotationPolicy: Always
    algorithm: RSA
    size: 4096
  usages:
    - server auth
  dnsNames:
    - metrics-server.kube-system.svc
  issuerRef:
    name: platform-deployment-metrics-server
    kind: Issuer
    group: cert-manager.io
