---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dex
  namespace: dex
spec:
  secretName: dex-cert
  duration: 24h0m0s
  renewBefore: 18h0m0s
  subject:
    organizations:
      - dex
  commonName: dex.dex.svc
  privateKey:
    rotationPolicy: Always
    algorithm: RSA
    size: 4096
  usages:
    - server auth
  dnsNames:
    - dex.dex.svc
    - ${ dex_hostname }
  issuerRef:
    name: vault-platform-deployment-core
    kind: ClusterIssuer
    group: cert-manager.io
