{{- if not ((.Values.platform.ingress.cloudflare).apiToken) }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-dns01-cloudflare
spec:
  destination:
    name: ''
    namespace: "{{ .Values.platform.ingress.name }}"
    server: 'https://kubernetes.default.svc'
  source:
    path: "{{ .Values.deployment.certManagerSelfsigned.path }}"
    repoURL: "{{ .Values.deployment.certManagerSelfsigned.repoURL }}"
    targetRevision: "{{ .Values.deployment.certManagerSelfsigned.targetRevision }}"
    helm:
      values: |-
        platform:
          ingress:
            name: "{{ .Values.platform.ingress.name }}"
            domain: "{{ .Values.platform.ingress.domain }}"

  project: "{{ .Values.core.projectName }}"
  syncPolicy:
    automated:
      prune: false
      selfHeal: {{ .Values.deployment.certManagerSelfsigned.selfHeal }}
{{- end }}
