---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress-controller
spec:
  destination:
    name: ''
    namespace: "{{ .Values.platform.ingress.name }}"
    server: 'https://kubernetes.default.svc'
  source:
    path: "{{ .Values.deployment.nginxIngressController.path }}"
    repoURL: "{{ .Values.deployment.nginxIngressController.repoURL }}"
    targetRevision: "{{ .Values.deployment.nginxIngressController.targetRevision }}"
    helm:
      values: |-
        platform:
          domain: "{{ .Values.platform.domain }}"
          ingress:
            name: "{{ .Values.platform.ingress.name }}"
            loadbalancerIP: "{{ .Values.platform.ingress.loadbalancerIP }}"
            label:
              name: "{{ .Values.platform.ingress.label.name }}"
              value: "{{ .Values.platform.ingress.label.value }}"
            taint:
              name: "{{ .Values.platform.ingress.taint.name }}"
              value: "{{ .Values.platform.ingress.taint.value }}"

  project: "{{ .Values.core.projectName }}"
  syncPolicy:
    automated:
      prune: false
      selfHeal: {{ .Values.deployment.nginxIngressController.selfHeal }}
