apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/kubernetes-sigs/external-dns/master/kustomize/external-dns-deployment.yaml
  - https://raw.githubusercontent.com/kubernetes-sigs/external-dns/master/kustomize/external-dns-serviceaccount.yaml
  - https://raw.githubusercontent.com/kubernetes-sigs/external-dns/master/kustomize/external-dns-clusterrole.yaml
  - https://raw.githubusercontent.com/kubernetes-sigs/external-dns/master/kustomize/external-dns-clusterrolebinding.yaml
  - secret.yaml
  - ./pod-disruption-budget.yaml

namespace: ${ external_dns_namespace }

images:
  - name: registry.k8s.io/external-dns/external-dns
    newTag: v0.13.1

patches:
- target:
    kind: ClusterRoleBinding
    name: external-dns-viewer
  patch: |-
    - op: replace
      path: /metadata/name
      value: external-dns-${ ingress_class_suffix }-viewer
- target:
    kind: ClusterRole
    name: external-dns
  patch: |-
    - op: replace
      path: /metadata/name
      value: external-dns-${ ingress_class_suffix }

- target:
    kind: Deployment
    name: external-dns
  patch: |-
    - op: add
      path: /spec/template/metadata/labels/rule.${platform_domain}~1allow-egress-api-server
      value: "true"
    - op: replace
      path: /spec/template/spec/containers/0/args
      value:
      - --source=ingress
      - --domain-filter=${ ingress_domain }
      - --provider=cloudflare
    - op: add
      path: /spec/template/spec/containers/0/env
      value:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: ingress-${ ingress_class_suffix }-cloudflare-api-token
            key: api-token
    - op: add
      path:  /spec/replicas
      value: 2
    - op: add
      path: /spec/template/spec/affinity
      value:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                app: external-dns
    - op: add
      path: /spec/template/spec/containers/0/resources
      value:
        limits:
          cpu: 100m
          memory: 32Mi
        requests:
          cpu: 10m
          memory: 16Mi
    - op: add
      path: /spec/template/spec/containers/0/securityContext
      value:
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        readOnlyRootFilesystem: true