---

- name: Retrieve a fresh snapshot
  hosts: etcd[0]
  become: true
  vars:
    etcd_data_path: /var/lib/etcd
    etcd_user: etcd
    etcd_group: etcd
  tasks:
  - name: Create a fresh Etcd snapshot
    become_user: "{{ etcd_user }}"
    ansible.builtin.shell: |
      . /etc/default/etcdctl
      etcdctl snapshot save /home/{{ etcd_user }}/etcd.snapshot

  - name: Retrieve the snapshot locally
    ansible.builtin.fetch:
      src: "/home/{{ etcd_user }}/etcd.snapshot"
      dest: "../artifacts/latest-etcd.snapshot"
      flat: true
