---

- name: Operator init
  hosts: vault[0]
  become: true
  vars:
    vault_artifacts_prefix: ""
    vault_unseal_data_dir: "{{ playbook_dir }}/../artifacts"
    vault_root_token_file: "{{ playbook_dir }}/../artifacts/{{ vault_artifacts_prefix }}root-token.txt"
    vault_key_shares: 1
    vault_key_threshold: 1
    vault_user: vault
    vault_environment:
      VAULT_ADDR: "https://{{ ansible_default_ipv4['address'] }}:8200"
      VAULT_CACERT: /var/vault/tls/ca.pem
      VAULT_CLIENT_CERT: /var/vault/tls/server.pem
      VAULT_CLIENT_KEY: /var/vault/tls/server.key
  tasks:
  - name: Initialise Vault
    become_user: "{{ vault_user }}"
    ansible.builtin.shell: |
      vault operator init \
        -key-shares={{ vault_key_shares }} \
        -key-threshold={{ vault_key_threshold }} \
        -format json
    environment: "{{ vault_environment }}"
    register: vault_init_data

  - name: Parse output
    ansible.builtin.set_fact:
      vault_init_parsed: "{{ vault_init_data.stdout | from_json }}"

  - name: Write unseal keys
    ansible.builtin.copy:
      dest: "{{ vault_unseal_data_dir }}/{{ vault_artifacts_prefix }}vault-unseal-key-{{ item.0 }}.txt"
      content: "{{ item.1 }}"
    with_indexed_items: "{{ vault_init_parsed.unseal_keys_hex }}"
    become: false
    delegate_to: localhost

  - name: Write Root Token
    ansible.builtin.copy:
      content: "{{ vault_init_parsed.root_token }}"
      dest: "{{ vault_root_token_file }}"
    become: false
    delegate_to: localhost
