---

- name: Enable TLS from Vault agent
  hosts: vault
  become: true
  tasks:
  - name: Remove cert
    ansible.builtin.file:
      path: /var/vault/tls/server.pem
      state: absent

  - name: Remove key
    ansible.builtin.file:
      path: /var/vault/tls/server.key
      state: absent

  - name: Start agent
    ansible.builtin.systemd:
      name: "vault-agent"
      state: restarted
      enabled: true

  - name: Start rclone-backup timer
    ansible.builtin.systemd:
      name: "rclone-backup.timer"
      state: started
      enabled: true
